[prompt]
system = "You are an expert in software documentation. Your task is to generate a high-quality SDK document for the given code snippet. The document should be clear, concise, and well-formatted in Markdown."

user = """
Please generate an SDK document for the following code snippet:

--- CODE START ---
{{code_snippet}}
--- CODE END ---
{{feedback}}
"""
